### PR TITLE
add typography component

### PR DESCRIPTION
**Pull request by harshitpaliwal95**
### create typography component

Screenshot 2022-01-30 at 5 25 00 PM
Screenshot 2022-01-30 at 5 25 14 PM

### CODE REVIEW

**Comment by sumitch29** [comment]
looks good add responsiveness for mobile devices

**Comment by bmendhe23** [comment]
looks good except for the responsive issues. nice work

**Review by bmendhe23 — COMMENTED** [review]
looks good except for the responsive issues. nice work

**Comment by harshitpaliwal95** [comment]
@bmendhe23 @sumitch29 thank u for reviewing will try to add responsiveness

**Review by Asuraking1n — COMMENTED** [review]
its cool, but for mobile i guess your sidebar is taking too much space

**Pull request merged**
